#!/bin/bash

find /var/www/html/ide/repos -type d -name '*.git' | while read gdir
do
    cd "$gdir"
    echo "$gdir"

    if [[ `git config core.bare` == "true" ]]
    then 
	git config receive.denyNonFastForwards true
    fi

    git config core.sharedRepository all

    chgrp www "$gdir" -R
    chmod g+rwX "$gdir" -R
    find "$gdir" -type d -print0 | xargs -0 chmod g+s
done