# Provides access to the team's IDE git repos via HTTPS

class www::teamgit( $ide_root_dir ) {

  # WARNING: this variable also appears as a literal below.
  $teams_conf_builder = '/usr/local/bin/team_repos_conf_builder.py'
  file { $teams_conf_builder:
    ensure => present,
    owner => 'root',
    group => 'root',
    mode => '0700',
    source => 'puppet:///modules/www/team_repos_conf_builder.py',
  }

  $anonpw = extlookup('ldap_anon_user_pw')
  file { '/usr/local/bin/team_repos_conf_template.conf':
    ensure => present,
    owner => 'root',
    group => 'root',
    mode => '0600',
    content => template('www/team_repos_conf_template.conf.erb'),
  }

  exec { 'create_team_git':
    command => "${teams_conf_builder} /etc/httpd/conf.d/teamgit.conf",
    cwd => '/usr/local/bin',
    require => [File[$teams_conf_builder],
                Package['python-ldap'], Exec['pop_ldap']],
    notify => Service['httpd'],
    user => 'root',
    provider => 'shell',

    # Puppet can't track the fact this this file is autogenerated. We could try
    # restarting the webserver every time, but that's unpleasent. So instead,
    # test to see whether any changes are going to occur, and only refresh if
    # they do.
    onlyif => '\
        tmpfile=`mktemp`;\
        /usr/local/bin/team_repos_conf_builder.py  $tmpfile;\
        cmp $tmpfile /etc/httpd/conf.d/teamgit.conf;\
        res=$?;\
        rm $tmpfile;\
        if test $res = 0; then\
            exit 1;\
        fi;\
        exit 0;'
  }
}
